### ISSUE TITLE
Please tag plugin versions

### ISSUE THREAD

**Issue by Rarst** [DaanRuiter/BlueBillywig-Wordpress-Plugin#1]
I understand that plugin isn't formally released yet, but it would be helpful if even early dev releases were tagged.

For my specific need that would be helpful to pull in plugin with Composer into a project.

**Comment by DaanRuiter** [comment]
Didn't think about that, will do so from now on.
Made a release for the current version: https://github.com/DaanRuiter/BlueBillywig-Wordpress-Plugin/releases/tag/0.3.1
